### PR TITLE
PR from Sarthak2601

### LINKED ISSUE #9: Sign Up Activity
Making a sign up activity for the user using Firebase through email and password.

### LINKED ISSUE #10: Google Sign-in
Adding google sign in authenticating option.

### LINKED ISSUE #11: Facebook Sign in
Creating a Facebook sign in option for signing in.

### LINKED ISSUE #13: Design a logo for the app

### LINKED ISSUE #21: Add Feature to change pitch and speed of speech

### LINKED ISSUE #23: Add Skip button
The app should have a skip login button, we should not force anyone to register.

### PR DESCRIPTION
**Pull request by Sarthak2601**
Fixes #13 
Fixes #23 
Fixes #21 
Fixes #10 
Fixes #11 
Fixes #9 

Changes: 
*Pitch can be set using seekbar now. 
*Speech rate can be set now. 
*Logo made and updated. 
*Splash updated. 
*Guest Login added so that user wouldn't need to register. (Skip Button Modification) 
*Google Sign in 
*Facebook Sign in 
*Sign in via Email/Password
*Sign up via Email/Password
*Firebase Connected 
*Facebook API connected 

RoboLogo
Screenshot_2019-12-09-22-48-25-014_io github njackwinterofcode robotalk
Screenshot_2019-12-09-22-48-35-553_io github njackwinterofcode robotalk

### CODE REVIEW

**Comment by somenath1435** [comment]
@Sarthak2601 There are unncessary commits, remove them

**Comment by somenath1435** [comment]
@Sarthak2601 Instead of writing fixes #issue1,2 
Write fixes #1 , fixes #2 like this

**Comment by Sarthak2601** [comment]
> @Sarthak2601 There are unncessary commits, remove them

I don't know how to. Can you please help?

**Comment by ShivangiSingh17** [comment]
@Sarthak2601 this will help: https://stackoverflow.com/questions/1338728/delete-commits-from-a-branch-in-git

**Comment by Sarthak2601** [comment]
@ShivangiSingh17 Mam, can you please check your Gitter account. Thanks.

**Pull request closed without merging**
